//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CajaBanco.IntegracionService1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cliente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CajaBanco.IntegracionService1.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CajaBanco.IntegracionService1.Cuenta CuentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        private System.DateTime FechaNacimientoField;
        
        private CajaBanco.IntegracionService1.eSexo SexoField;
        
        private CajaBanco.IntegracionService1.eEstadoCivil EstadoCivilField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public CajaBanco.IntegracionService1.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombres {
            get {
                return this.NombresField;
            }
            set {
                if ((object.ReferenceEquals(this.NombresField, value) != true)) {
                    this.NombresField = value;
                    this.RaisePropertyChanged("Nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellidos {
            get {
                return this.ApellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidosField, value) != true)) {
                    this.ApellidosField = value;
                    this.RaisePropertyChanged("Apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Identificador {
            get {
                return this.IdentificadorField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificadorField, value) != true)) {
                    this.IdentificadorField = value;
                    this.RaisePropertyChanged("Identificador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public CajaBanco.IntegracionService1.Cuenta Cuenta {
            get {
                return this.CuentaField;
            }
            set {
                if ((object.ReferenceEquals(this.CuentaField, value) != true)) {
                    this.CuentaField = value;
                    this.RaisePropertyChanged("Cuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public CajaBanco.IntegracionService1.eSexo Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public CajaBanco.IntegracionService1.eEstadoCivil EstadoCivil {
            get {
                return this.EstadoCivilField;
            }
            set {
                if ((this.EstadoCivilField.Equals(value) != true)) {
                    this.EstadoCivilField = value;
                    this.RaisePropertyChanged("EstadoCivil");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Cuenta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CajaBanco.IntegracionService1.ExtensionDataObject ExtensionData1Field;
        
        private int NumeroCuentaField;
        
        private double BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CajaBanco.IntegracionService1.Cliente ClienteField;
        
        private System.DateTime FechaCreacionField;
        
        private CajaBanco.IntegracionService1.eTipoCuenta TipoCuentaField;
        
        private System.DateTime FechaActualizacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public CajaBanco.IntegracionService1.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int NumeroCuenta {
            get {
                return this.NumeroCuentaField;
            }
            set {
                if ((this.NumeroCuentaField.Equals(value) != true)) {
                    this.NumeroCuentaField = value;
                    this.RaisePropertyChanged("NumeroCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Balance {
            get {
                return this.BalanceField;
            }
            set {
                if ((this.BalanceField.Equals(value) != true)) {
                    this.BalanceField = value;
                    this.RaisePropertyChanged("Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public CajaBanco.IntegracionService1.Cliente Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaCreacion {
            get {
                return this.FechaCreacionField;
            }
            set {
                if ((this.FechaCreacionField.Equals(value) != true)) {
                    this.FechaCreacionField = value;
                    this.RaisePropertyChanged("FechaCreacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public CajaBanco.IntegracionService1.eTipoCuenta TipoCuenta {
            get {
                return this.TipoCuentaField;
            }
            set {
                if ((this.TipoCuentaField.Equals(value) != true)) {
                    this.TipoCuentaField = value;
                    this.RaisePropertyChanged("TipoCuenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime FechaActualizacion {
            get {
                return this.FechaActualizacionField;
            }
            set {
                if ((this.FechaActualizacionField.Equals(value) != true)) {
                    this.FechaActualizacionField = value;
                    this.RaisePropertyChanged("FechaActualizacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eSexo", Namespace="http://tempuri.org/")]
    public enum eSexo : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Femenino = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eEstadoCivil", Namespace="http://tempuri.org/")]
    public enum eEstadoCivil : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Soltero = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Casado = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="eTipoCuenta", Namespace="http://tempuri.org/")]
    public enum eTipoCuenta : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Corriente = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Compartida = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntegracionService1.CajaServiceSoap")]
    public interface CajaServiceSoap {
        
        // CODEGEN: Generating message contract since element name Pcedula from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCliente", ReplyAction="*")]
        CajaBanco.IntegracionService1.ValidarClienteResponse ValidarCliente(CajaBanco.IntegracionService1.ValidarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<CajaBanco.IntegracionService1.ValidarClienteResponse> ValidarClienteAsync(CajaBanco.IntegracionService1.ValidarClienteRequest request);
        
        // CODEGEN: Generating message contract since element name DummyResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dummy", ReplyAction="*")]
        CajaBanco.IntegracionService1.DummyResponse Dummy(CajaBanco.IntegracionService1.DummyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Dummy", ReplyAction="*")]
        System.Threading.Tasks.Task<CajaBanco.IntegracionService1.DummyResponse> DummyAsync(CajaBanco.IntegracionService1.DummyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarCliente", Namespace="http://tempuri.org/", Order=0)]
        public CajaBanco.IntegracionService1.ValidarClienteRequestBody Body;
        
        public ValidarClienteRequest() {
        }
        
        public ValidarClienteRequest(CajaBanco.IntegracionService1.ValidarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Pcedula;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string PidCajero;
        
        public ValidarClienteRequestBody() {
        }
        
        public ValidarClienteRequestBody(string Pcedula, string PidCajero) {
            this.Pcedula = Pcedula;
            this.PidCajero = PidCajero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public CajaBanco.IntegracionService1.ValidarClienteResponseBody Body;
        
        public ValidarClienteResponse() {
        }
        
        public ValidarClienteResponse(CajaBanco.IntegracionService1.ValidarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CajaBanco.IntegracionService1.Cliente ValidarClienteResult;
        
        public ValidarClienteResponseBody() {
        }
        
        public ValidarClienteResponseBody(CajaBanco.IntegracionService1.Cliente ValidarClienteResult) {
            this.ValidarClienteResult = ValidarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Dummy", Namespace="http://tempuri.org/", Order=0)]
        public CajaBanco.IntegracionService1.DummyRequestBody Body;
        
        public DummyRequest() {
        }
        
        public DummyRequest(CajaBanco.IntegracionService1.DummyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DummyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PidCajero;
        
        public DummyRequestBody() {
        }
        
        public DummyRequestBody(int PidCajero) {
            this.PidCajero = PidCajero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DummyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DummyResponse", Namespace="http://tempuri.org/", Order=0)]
        public CajaBanco.IntegracionService1.DummyResponseBody Body;
        
        public DummyResponse() {
        }
        
        public DummyResponse(CajaBanco.IntegracionService1.DummyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DummyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DummyResult;
        
        public DummyResponseBody() {
        }
        
        public DummyResponseBody(string DummyResult) {
            this.DummyResult = DummyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CajaServiceSoapChannel : CajaBanco.IntegracionService1.CajaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CajaServiceSoapClient : System.ServiceModel.ClientBase<CajaBanco.IntegracionService1.CajaServiceSoap>, CajaBanco.IntegracionService1.CajaServiceSoap {
        
        public CajaServiceSoapClient() {
        }
        
        public CajaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CajaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CajaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CajaBanco.IntegracionService1.ValidarClienteResponse CajaBanco.IntegracionService1.CajaServiceSoap.ValidarCliente(CajaBanco.IntegracionService1.ValidarClienteRequest request) {
            return base.Channel.ValidarCliente(request);
        }
        
        public CajaBanco.IntegracionService1.Cliente ValidarCliente(string Pcedula, string PidCajero) {
            CajaBanco.IntegracionService1.ValidarClienteRequest inValue = new CajaBanco.IntegracionService1.ValidarClienteRequest();
            inValue.Body = new CajaBanco.IntegracionService1.ValidarClienteRequestBody();
            inValue.Body.Pcedula = Pcedula;
            inValue.Body.PidCajero = PidCajero;
            CajaBanco.IntegracionService1.ValidarClienteResponse retVal = ((CajaBanco.IntegracionService1.CajaServiceSoap)(this)).ValidarCliente(inValue);
            return retVal.Body.ValidarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CajaBanco.IntegracionService1.ValidarClienteResponse> CajaBanco.IntegracionService1.CajaServiceSoap.ValidarClienteAsync(CajaBanco.IntegracionService1.ValidarClienteRequest request) {
            return base.Channel.ValidarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CajaBanco.IntegracionService1.ValidarClienteResponse> ValidarClienteAsync(string Pcedula, string PidCajero) {
            CajaBanco.IntegracionService1.ValidarClienteRequest inValue = new CajaBanco.IntegracionService1.ValidarClienteRequest();
            inValue.Body = new CajaBanco.IntegracionService1.ValidarClienteRequestBody();
            inValue.Body.Pcedula = Pcedula;
            inValue.Body.PidCajero = PidCajero;
            return ((CajaBanco.IntegracionService1.CajaServiceSoap)(this)).ValidarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CajaBanco.IntegracionService1.DummyResponse CajaBanco.IntegracionService1.CajaServiceSoap.Dummy(CajaBanco.IntegracionService1.DummyRequest request) {
            return base.Channel.Dummy(request);
        }
        
        public string Dummy(int PidCajero) {
            CajaBanco.IntegracionService1.DummyRequest inValue = new CajaBanco.IntegracionService1.DummyRequest();
            inValue.Body = new CajaBanco.IntegracionService1.DummyRequestBody();
            inValue.Body.PidCajero = PidCajero;
            CajaBanco.IntegracionService1.DummyResponse retVal = ((CajaBanco.IntegracionService1.CajaServiceSoap)(this)).Dummy(inValue);
            return retVal.Body.DummyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CajaBanco.IntegracionService1.DummyResponse> CajaBanco.IntegracionService1.CajaServiceSoap.DummyAsync(CajaBanco.IntegracionService1.DummyRequest request) {
            return base.Channel.DummyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CajaBanco.IntegracionService1.DummyResponse> DummyAsync(int PidCajero) {
            CajaBanco.IntegracionService1.DummyRequest inValue = new CajaBanco.IntegracionService1.DummyRequest();
            inValue.Body = new CajaBanco.IntegracionService1.DummyRequestBody();
            inValue.Body.PidCajero = PidCajero;
            return ((CajaBanco.IntegracionService1.CajaServiceSoap)(this)).DummyAsync(inValue);
        }
    }
}
